### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by mkirchner** [mkirchner/stutter#9]
Incomplete TODO list in no particular order:

- [ ] Documentation
- [x] Clean up `const` guarantees
- [ ] Builtin functions
  - [x] true, false, nil
  - [x] add, minus, mul, div
  - [x] eq, leq, geq
  - [x] cons
  - [x] car / head
  - [x] cdr / tail
  - [ ] map
  - [ ] hash-map
    - [ ] at
- [ ] Closures: works in principle but envs have pointer semantics, so `set!` breaks closures :(
- [x] macros
- [x] TCO

**Comment by mkirchner** [comment]
Closing this in favor of simpler tracking on the README page.
